# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160225_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contract_length',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Summer', 'Summer'), ('Winter', 'Winter'), ('Fall/Winter', 'Fall/Winter'), ('Winter/Summer', 'Winter/Summer'), ('Summer/Fall', 'Summer/Fall'), ('Full Year', 'Full Year'), ('Other', 'Other'), ('No Contract', 'No Contract')], default='Fall/Winter', max_length=15),
        ),
    ]
